---
- name: Setup ubuntu workstation
  hosts: localhost
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Kitty terminal emulator
      shell: curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin
      args:
        executable: /bin/bash

    - name: Install tmux
      apt:
        name: tmux
        state: present

    - name: Install fish shell
      apt:
        name: fish
        state: present

    - name: Install Survex
      apt:
        name: survex
        state: present
    
    - name: Install fzf
      apt:
        name: fzf
        state: present
    
    - name: Change shell to fish
      shell: chsh -s $(which fish)
